# Generated by Django 4.2.3 on 2023-07-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='asd', max_length=254),
            preserve_default=False,
        ),
    ]
